version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: reservation
    platform: linux/x86_64
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: reservation
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - ./db/mysql/data:/var/lib/mysql
