version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME=: admin
      DB_PASSWORD: admin1234
      DB_DATABASE: reservation
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
  db:
    image: mysql
    platform: linux/x86_64
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: reservation
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - ./db/mysql/data:/var/lib/mysql
  redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'

volumes:
  mysql-data:
  redis-data:
